### ISSUE TITLE
ModuleNotFoundError while running package example

### ISSUE THREAD

**Issue by LouisStef** [bruce-szalwinski/mkdocs-typer#19]
### Issue

Hi thank you for supporting this package ❤️

I can't get the package example working. I am using an old version of the package 0.0.2 (can't update for project reasons), python 3.9.18

Mkdocs-typer doesn't find the `app` module ...

#### Project file structure
```console
tree
.
├── app
│   ├── __init__.py
│   └── cli.py
├── docs
│   ├── index.md
│   └── typer.md
└── mkdocs.yml

```

```python
# app/cli.py
import typer

my_app = typer.Typer()


@my_app.command()
def foo():
    """do something fooey"""


@my_app.callback()
def cli():
    """
    Main entrypoint for this dummy program
    """
```

```
# typer.md

This page provides documentation for our command line tools.

::: mkdocs-typer
    :module: app.cli
    :command: cli

```

```console
$ mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
ERROR   -  Error reading page 'typer.md': No module named 'app'
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/env-doc/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 98, in serve
    builder(config)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 79, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/mkdocs/commands/build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/mkdocs/commands/build.py", line 175, in _populate_page
    page.render(config, files)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/mkdocs/structure/pages.py", line 271, in render
    self.content = md.convert(self.markdown)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/markdown/core.py", line 354, in convert
    self.lines = prep.run(self.lines)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/mkdocs_typer/_extension.py", line 31, in run
    return list(replace_blocks(lines, title="mkdocs-typer", replace=replace_command_docs))
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/mkdocs_typer/_processing.py", line 34, in replace_blocks
    yield from replace(**options)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/mkdocs_typer/_extension.py", line 24, in replace_command_docs
    command_obj = load_command(module, command)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/mkdocs_typer/_loader.py", line 14, in load_command
    command = _load_obj(module, attribute)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/site-packages/mkdocs_typer/_loader.py", line 24, in _load_obj
    mod = importlib.import_module(module)
  File "/opt/homebrew/anaconda3/envs/env-doc/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
``` 

#### Conda env
```console
Package                    Version
-------------------------- ----------
certifi                    2023.11.17
charset-normalizer         3.3.2
click                      8.1.7
colorama                   0.4.6
ghp-import                 2.1.0
griffe                     0.38.1
idna                       3.6
importlib-metadata         7.0.0
Jinja2                     3.1.2
Markdown                   3.5.1
MarkupSafe                 2.1.3
mergedeep                  1.3.4
mkdocs                     1.5.1
mkdocs-autorefs            0.4.1
mkdocs-material            9.1.21
mkdocs-material-extensions 1.3.1
mkdocs-typer               0.0.2
mkdocstrings               0.24.0
mkdocstrings-python        0.8.3
packaging                  23.2
pathspec                   0.12.1
pip                        23.3.1
platformdirs               4.1.0
Pygments                   2.17.2
pymdown-extensions         10.5
python-dateutil            2.8.2
PyYAML                     6.0.1
pyyaml_env_tag             0.1
regex                      2023.10.3
requests                   2.31.0
setuptools                 68.2.2
six                        1.16.0
typer                      0.9.0
typing_extensions          4.9.0
urllib3                    2.1.0
watchdog                   3.0.0
wheel                      0.42.0
zipp                       3.17.0
```

**Comment by LouisStef** [comment]
I think I had an issue with my libs. Reinstalling everything in a new env using poetry fixed it.
